services:
  youtubelinks.api:
    image: ${DOCKER_REGISTRY-}youtubelinksapi
    container_name: youtubelinks.api
    build:
      context: .
      dockerfile: YoutubeLinks.Api/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./YoutubeLinks.Api/Logging/Logs:/app/Logging/Logs

  youtubelinks.blazor:
    image: ${DOCKER_REGISTRY-}youtubelinksblazor
    container_name: youtubelinks.blazor
    build:
      context: .
      dockerfile: YoutubeLinks.Blazor/Dockerfile
    ports:
      - 7000:80
    environment:
      - ASPNETCORE_URLS=http://+:7000
      - ASPNETCORE_HTTP_PORTS=7000
      - ASPNETCORE_ENVIRONMENT=Development
      
  youtubelinks.database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: youtubelinks.database
    shm_size: 4gb
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: 'Password1!'
      ACCEPT_EULA: 'Y'
    volumes:
      - mssql_volume:/var/opt/mssql

  youtubelinks.seq:
    image: datalust/seq:latest
    container_name: youtubelinks.seq
    ports:
      - 5341:5341
      - 8081:80
    environment:
      ACCEPT_EULA: 'Y'
      
volumes:
  mssql_volume:
    driver: local